// customer-app/src/pages/Dashboard.jsx
import React, { useEffect, useState, useContext } from 'react';
import { AuthContext } from '../context/AuthContext';
import api from '../services/api';
import { Link } from 'react-router-dom';

const Dashboard = () => {
  const { user } = useContext(AuthContext);
  const [stats, setStats] = useState({ pending: 0, active: 0, completed: 0 });
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchBookings = async () => {
      try {
        const { data } = await api.get('/bookings/my');
        let pending = 0, active = 0, completed = 0;
        data.forEach(b => {
          if (b.status === 'pending') pending++;
          else if (b.status === 'completed') completed++;
          else if (b.status !== 'cancelled') active++;
        });
        setStats({ pending, active, completed });
      } catch (error) {
        console.error('Failed to fetch bookings', error);
      } finally {
        setLoading(false);
      }
    };
    fetchBookings();
  }, []);

  const firstName = user?.name?.split(' ')[0] || 'Customer';

  return (
    <div className="page-content">
      <div className="dashboard-welcome">
        <h2>Good day, {firstName}! 👋</h2>
        <p>Here's a summary of your borewell drilling requests.</p>
      </div>

      <div className="dashboard-stats">
        <div className="stat-card">
          <div className="stat-icon pending">⏳</div>
          <div>
            <h3>Pending</h3>
            <p>{loading ? '–' : stats.pending}</p>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon active">🔨</div>
          <div>
            <h3>Active</h3>
            <p>{loading ? '–' : stats.active}</p>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon completed">✅</div>
          <div>
            <h3>Completed</h3>
            <p>{loading ? '–' : stats.completed}</p>
          </div>
        </div>
      </div>

      <div className="dashboard-cta">
        <div className="empty-state-icon">💧</div>
        <h3>Need a borewell drilled?</h3>
        <p>Submit a drilling request and a verified contractor will be assigned to your location.</p>
        <Link to="/book-drilling" className="btn btn-primary">
          + Book Drilling Service
        </Link>
      </div>
    </div>
  );
};

export default Dashboard;

// owner-app/src/app/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { BookingService } from '../services/booking.service';
import { AuthService } from '../services/auth.service';

@Component({
  selector: 'app-dashboard',
  template: `
    <div class="page-content">
      <div class="dashboard-welcome">
        <h2>Good day, {{ownerName}}! 👷</h2>
        <p>Here's an overview of your drilling jobs and pending requests.</p>
      </div>

      <div class="dashboard-stats">
        <div class="stat-card">
          <div class="stat-icon requests">📋</div>
          <div>
            <h3>Available Requests</h3>
            <p>{{loading ? '–' : availableCount}}</p>
          </div>
        </div>
        <div class="stat-card">
          <div class="stat-icon active">🔨</div>
          <div>
            <h3>Active Jobs</h3>
            <p>{{loading ? '–' : activeCount}}</p>
          </div>
        </div>
        <div class="stat-card">
          <div class="stat-icon completed">✅</div>
          <div>
            <h3>Completed Jobs</h3>
            <p>{{loading ? '–' : completedCount}}</p>
          </div>
        </div>
      </div>

      <div class="empty-state" *ngIf="!loading && availableCount === 0 && activeCount === 0">
        <div class="empty-state-icon">🏗️</div>
        <h3>No activity yet</h3>
        <p>Check "Available Requests" to start accepting drilling jobs!</p>
      </div>
    </div>
  `
})
export class DashboardComponent implements OnInit {
  ownerName = 'Contractor';
  availableCount = 0;
  activeCount = 0;
  completedCount = 0;
  loading = true;

  constructor(private bookingService: BookingService, private authService: AuthService) {}

  ngOnInit() {
    const user = this.authService.getCurrentUser();
    if (user?.name) {
      this.ownerName = user.name.split(' ')[0];
    }

    Promise.all([
      this.bookingService.getAvailableRequests().toPromise(),
      this.bookingService.getAssignedJobs().toPromise()
    ]).then(([available, assigned]: any) => {
      this.availableCount = available?.length || 0;
      let active = 0, completed = 0;
      (assigned || []).forEach((b: any) => {
        if (b.status === 'completed') completed++;
        else active++;
      });
      this.activeCount = active;
      this.completedCount = completed;
      this.loading = false;
    }).catch(() => {
      this.loading = false;
    });
  }
}
