// owner-app/src/app/auth/login/login.component.ts
import { Component } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  template: `
    <div class="auth-wrapper">
      <div class="auth-container">
        <div class="auth-logo">
          <div class="auth-logo-icon">🏗️</div>
          <h2>Owner Sign In</h2>
          <p class="auth-sub">Sign in to your InRand contractor account</p>
        </div>
        <div class="error-msg" *ngIf="error">{{error}}</div>
        <form (ngSubmit)="onSubmit()" #f="ngForm">
          <div class="form-group">
            <label>Email or Phone Number</label>
            <input type="text" [(ngModel)]="identifier" name="identifier" placeholder="Enter your email or phone" required>
          </div>
          <div class="form-group">
            <label>Password</label>
            <input type="password" [(ngModel)]="password" name="password" placeholder="Enter your password" required>
          </div>
          <button type="submit" class="btn btn-primary" style="width:100%;" [disabled]="loading">
            {{ loading ? '⏳ Signing in...' : '🔐 Sign In' }}
          </button>
        </form>
        <div class="text-center">
          Don't have an account? <a routerLink="/signup">Register as contractor →</a>
        </div>
      </div>
    </div>
  `
})
export class LoginComponent {
  identifier = '';
  password = '';
  error = '';
  loading = false;

  constructor(private authService: AuthService, private router: Router) {}

  onSubmit() {
    this.loading = true;
    this.error = '';
    this.authService.login(this.identifier, this.password).subscribe({
      next: () => this.router.navigate(['/']),
      error: (err) => {
        this.loading = false;
        if (err.error?.unverified) {
          this.router.navigate(['/verify-otp'], { queryParams: { identifier: this.identifier } });
        } else {
          this.error = err.error?.message || 'Invalid credentials. Please try again.';
        }
      }
    });
  }
}

// customer-app/src/pages/Login.jsx
import React, { useState, useContext } from 'react';
import { AuthContext } from '../context/AuthContext';
import { useNavigate, Link } from 'react-router-dom';

const Login = () => {
  const [identifier, setIdentifier] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const { login } = useContext(AuthContext);
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    try {
      await login(identifier, password);
      navigate('/');
    } catch (err) {
      if (err.response?.data?.unverified) {
        navigate('/verify-otp', { state: { identifier } });
      } else {
        setError(err.response?.data?.message || 'Invalid credentials. Please try again.');
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="auth-wrapper">
      <div className="auth-container">
        <div className="auth-logo">
          <div className="auth-logo-icon">💧</div>
          <h2>Welcome back</h2>
          <p className="auth-sub">Sign in to your InRand customer account</p>
        </div>
        {error && <div className="error-msg">{error}</div>}
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label>Email or Phone Number</label>
            <input type="text" value={identifier} onChange={e => setIdentifier(e.target.value)} placeholder="Enter your email or phone" required />
          </div>
          <div className="form-group">
            <label>Password</label>
            <input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter your password" required />
          </div>
          <button type="submit" className="btn btn-primary btn-full" disabled={loading}>
            {loading ? '⏳ Signing in...' : '🔐 Sign In'}
          </button>
        </form>
        <div className="text-center">
          Don't have an account? <Link to="/signup">Create one →</Link>
        </div>
      </div>
    </div>
  );
};

export default Login;
