// owner-app/src/app/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { AuthService } from '../services/auth.service';

@Component({
  selector: 'app-profile',
  template: `
    <div class="page-content">
      <div class="profile-container">
        <div class="profile-header">
          <div class="profile-avatar">{{nameInitial}}</div>
          <h2>{{user.name || 'Your Profile'}}</h2>
          <span>Borewell Contractor · InRand</span>
        </div>
        <div class="profile-body">
          <div class="success-msg" *ngIf="message && !message.includes('Failed')">✅ {{message}}</div>
          <div class="error-msg" *ngIf="message && message.includes('Failed')">{{message}}</div>
          <form (ngSubmit)="onSubmit()" #f="ngForm">
            <div style="margin-bottom:20px; padding-bottom:16px; border-bottom:1px solid #e5e7eb;">
              <p style="font-size:0.8rem;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;color:#6b7280;margin-bottom:14px;">Personal Info</p>
              <div class="form-group">
                <label>Full Name</label>
                <input type="text" [(ngModel)]="user.name" name="name" required placeholder="Your full name">
              </div>
              <div class="form-group">
                <label>Email Address</label>
                <input type="email" [(ngModel)]="user.email" name="email" placeholder="your@email.com">
              </div>
              <div class="form-group">
                <label>Phone Number</label>
                <input type="text" [(ngModel)]="user.phone" name="phone" placeholder="+91 98765 43210">
              </div>
            </div>
            <div style="margin-bottom:20px;">
              <p style="font-size:0.8rem;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;color:#6b7280;margin-bottom:14px;">Business Info</p>
              <div class="form-group">
                <label>Business / Company Name</label>
                <input type="text" [(ngModel)]="user.businessName" name="businessName" placeholder="e.g. Kumar Drilling Services">
              </div>
              <div class="form-group">
                <label>Service Area</label>
                <input type="text" [(ngModel)]="user.serviceArea" name="serviceArea" placeholder="e.g. Rajasthan, Gujarat">
              </div>
              <div class="form-group">
                <label>Years of Experience</label>
                <input type="number" [(ngModel)]="user.experienceYears" name="experienceYears" placeholder="e.g. 8">
              </div>
            </div>
            <button type="submit" class="btn btn-primary" style="width:100%;" [disabled]="loading">
              {{ loading ? '⏳ Saving...' : '💾 Save Changes' }}
            </button>
          </form>
        </div>
      </div>
    </div>
  `
})
export class ProfileComponent implements OnInit {
  user: any = { name: '', email: '', phone: '', businessName: '', serviceArea: '', experienceYears: null };
  message = '';
  loading = false;
  nameInitial = '?';

  constructor(private http: HttpClient, private authService: AuthService) {}

  ngOnInit() {
    this.http.get('http://localhost:5000/api/users/me').subscribe({
      next: (data: any) => {
        this.user = {
          name: data.name || '',
          email: data.email || '',
          phone: data.phone || '',
          businessName: data.businessName || '',
          serviceArea: data.serviceArea || '',
          experienceYears: data.experienceYears || null
        };
        this.nameInitial = (data.name || '?').charAt(0).toUpperCase();
      },
      error: () => {}
    });
  }

  onSubmit() {
    this.loading = true;
    this.message = '';
    this.http.put('http://localhost:5000/api/users/me', this.user).subscribe({
      next: () => {
        this.loading = false;
        this.message = 'Profile updated successfully!';
        this.nameInitial = (this.user.name || '?').charAt(0).toUpperCase();
        setTimeout(() => this.message = '', 4000);
      },
      error: () => {
        this.loading = false;
        this.message = 'Failed to update profile. Please try again.';
      }
    });
  }
}

// customer-app/src/pages/Profile.jsx
import React, { useState, useEffect, useContext } from 'react';
import { AuthContext } from '../context/AuthContext';
import api from '../services/api';

const Profile = () => {
  const { user } = useContext(AuthContext);
  const [formData, setFormData] = useState({ name: '', email: '', phone: '' });
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const fetchProfile = async () => {
      try {
        const { data } = await api.get('/users/me');
        setFormData({ name: data.name || '', email: data.email || '', phone: data.phone || '' });
      } catch (err) {
        console.error(err);
      }
    };
    fetchProfile();
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setMessage('');
    try {
      await api.put('/users/me', formData);
      setMessage('success');
    } catch {
      setMessage('error');
    } finally {
      setLoading(false);
      setTimeout(() => setMessage(''), 4000);
    }
  };

  const nameInitial = (formData.name || user?.name || '?').charAt(0).toUpperCase();

  return (
    <div className="page-content">
      <div className="profile-container">
        <div className="profile-header">
          <div className="profile-avatar">{nameInitial}</div>
          <h2>{formData.name || 'Your Profile'}</h2>
          <span>Customer · InRand</span>
        </div>
        <div className="profile-body">
          {message === 'success' && <div className="success-msg">✅ Profile updated successfully!</div>}
          {message === 'error' && <div className="error-msg">Failed to update profile. Please try again.</div>}
          <form onSubmit={handleSubmit}>
            <div className="form-group">
              <label>Full Name</label>
              <input type="text" value={formData.name} onChange={e => setFormData({ ...formData, name: e.target.value })} placeholder="Your full name" required />
            </div>
            <div className="form-group">
              <label>Email Address</label>
              <input type="email" value={formData.email} onChange={e => setFormData({ ...formData, email: e.target.value })} placeholder="your@email.com" />
            </div>
            <div className="form-group">
              <label>Phone Number</label>
              <input type="text" value={formData.phone} onChange={e => setFormData({ ...formData, phone: e.target.value })} placeholder="+91 98765 43210" />
            </div>
            <button type="submit" className="btn btn-primary btn-full" disabled={loading}>
              {loading ? '⏳ Saving...' : '💾 Save Changes'}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
};

export default Profile;
