// owner-app/src/app/auth/verify-otp/verify-otp.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { Router, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-verify-otp',
  template: `
    <div class="auth-wrapper">
      <div class="auth-container">
        <div class="auth-logo">
          <div class="auth-logo-icon">✉️</div>
          <h2>Verify Your Account</h2>
          <p class="auth-sub">Enter the 6-digit OTP sent to<br><strong>{{identifier}}</strong></p>
        </div>
        <div class="error-msg" *ngIf="error">{{error}}</div>
        <form (ngSubmit)="onSubmit()" #f="ngForm">
          <div class="form-group">
            <label>OTP Code</label>
            <input
              type="text"
              [(ngModel)]="otp"
              name="otp"
              placeholder="Enter 6-digit OTP"
              required
              maxlength="6"
              style="font-size: 1.4rem; letter-spacing: 0.3em; text-align: center; font-weight: 700;"
            >
          </div>
          <button type="submit" class="btn btn-primary" style="width:100%;" [disabled]="loading">
            {{ loading ? '⏳ Verifying...' : '✅ Verify & Continue' }}
          </button>
        </form>
        <div class="text-center" style="margin-top: 14px;">
          <a routerLink="/login" style="color: #6b7280;">← Back to Login</a>
        </div>
      </div>
    </div>
  `
})
export class VerifyOtpComponent implements OnInit {
  otp = '';
  identifier = '';
  error = '';
  loading = false;

  constructor(
    private authService: AuthService,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  ngOnInit() {
    this.route.queryParams.subscribe(params => {
      this.identifier = params['identifier'];
      if (!this.identifier) {
        this.router.navigate(['/login']);
      }
    });
  }

  onSubmit() {
    this.loading = true;
    this.error = '';
    this.authService.verifyOtp(this.identifier, this.otp).subscribe({
      next: () => this.router.navigate(['/']),
      error: (err) => {
        this.loading = false;
        this.error = err.error?.message || 'Verification failed. Check your OTP and try again.';
      }
    });
  }
}

// customer-app/src/pages/VerifyOtp.jsx
import React, { useState, useContext } from 'react';
import { AuthContext } from '../context/AuthContext';
import { useNavigate, useLocation, Link } from 'react-router-dom';

const VerifyOtp = () => {
  const [otp, setOtp] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const { verifyOtp } = useContext(AuthContext);
  const navigate = useNavigate();
  const location = useLocation();
  const identifier = location.state?.identifier;

  if (!identifier) {
    navigate('/login');
    return null;
  }

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    try {
      await verifyOtp(identifier, otp);
      navigate('/');
    } catch (err) {
      setError(err.response?.data?.message || 'Verification failed. Check your OTP and try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="auth-wrapper">
      <div className="auth-container">
        <div className="auth-logo">
          <div className="auth-logo-icon">✉️</div>
          <h2>Verify Your Account</h2>
          <p className="auth-sub">
            Enter the 6-digit OTP sent to<br />
            <strong style={{ color: '#0B72B9' }}>{identifier}</strong>
          </p>
        </div>
        {error && <div className="error-msg">{error}</div>}
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label>OTP Code</label>
            <input
              type="text"
              value={otp}
              onChange={e => setOtp(e.target.value)}
              placeholder="Enter 6-digit OTP"
              required
              maxLength="6"
              style={{ fontSize: '1.5rem', letterSpacing: '0.3em', textAlign: 'center', fontWeight: '700' }}
            />
          </div>
          <button type="submit" className="btn btn-primary btn-full" disabled={loading}>
            {loading ? '⏳ Verifying...' : '✅ Verify & Continue'}
          </button>
        </form>
        <div className="text-center" style={{ marginTop: 14 }}>
          <Link to="/login" style={{ color: '#6b7280' }}>← Back to Login</Link>
        </div>
      </div>
    </div>
  );
};

export default VerifyOtp;
